### ISSUE TITLE
[project] only show project name

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#128]
<img width="233" alt="圖片" src="https://user-images.githubusercontent.com/22004511/121771319-456ee200-cba1-11eb-9eb5-e73b1de6fe99.png">

should only show "sauron", rather than full path.

**Comment by smallfont00** [comment]
like this?
![image](https://user-images.githubusercontent.com/33400198/121784915-5b07fa00-cbe9-11eb-9497-ace13331bda0.png)

**Comment by dannypsnl** [comment]
Done
