### ISSUE TITLE
[bug:project] project viewer should work on windows 10

### ISSUE THREAD

**Issue by smallfont00** [racket-tw/sauron#133]
**Describe the bug**
Project viewer is not working on windows 10

**To Reproduce**
1. ctrl + y
2. nothing happen

**Expected behavior**
something like that
![image](https://user-images.githubusercontent.com/33400198/121783897-eaaaaa00-cbe3-11eb-9454-5b5cf226b039.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.0.3

**Comment by dannypsnl** [comment]
@SmallFont00 I don't have any windows machine, can you fix this?

**Comment by smallfont00** [comment]
@dannypsnl sure.

**Comment by smallfont00** [comment]
The problem is caused by key binding conflict on Windows OS. The Undo key is ctrl + y on Windows but ctrl + shift + z on Linux.

**Comment by dannypsnl** [comment]
Done by #135
