### ISSUE TITLE
[bug] c+y dead on MacOS

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#162]
@SmallFont00 Can you take a look and detect how many OS are affected?

### Update

OS: Windows, MacOS

**Comment by smallfont00** [comment]
c+y works on my ubuntu 20.04 (in Hyper-V). 
c+s+y works on my windows. 

I don't have any machine running MacOS .

**Comment by smallfont00** [comment]
In Ubuntu, c+y would be the same as c+m if you didn't choose a project in the first place.
But this functionality didn't work in Windows.
I don't know whether this is what you're asking.

**Comment by dannypsnl** [comment]
My case is, after c+m, c+y works. Before c+m, c+y shall trigger c+m but doesn't

**Comment by smallfont00** [comment]
I see. Windows has the same issue.

**Comment by dannypsnl** [comment]
I think you probably don't update Ubuntu code, bug is introduced by https://github.com/racket-tw/sauron/commit/9b38da3d94214c83519f983652e2b5044dfb108b

**Comment by smallfont00** [comment]
Hmmmmm.....

**Comment by smallfont00** [comment]
Yeah, one should `git pull` after `git fetch --all` for existed branch.
