### ISSUE TITLE
ffi-lib: could not load foreign library   path: libedit-3.dll

### ISSUE THREAD

**Issue by spdegabrielle** [racket-tw/sauron#174]
**Describe the bug**
Create project fails

**To Reproduce**
1. ctrl-m
2. Select 'create project' 
3. Select location
4. name project
5. select template 'gui-app'  
6. 'Dr Racket Internal Error' error box with the error text below

**Expected behavior**
Create gui library

**Screenshots(or error message)**

```
ffi-lib: could not load foreign library
  path: libedit-3.dll
  system error: The specified module could not be found.; win_err=126
  context...:
   C:\Program Files\Racket\collects\ffi\unsafe.rkt:131:0: get-ffi-lib
   body of "C:\Program Files\Racket\share\pkgs\readline-lib\readline\rktrl.rkt"
   C:\Users\stde\AppData\Roaming\Racket\8.3\pkgs\sauron\project\manager.rkt:96:18
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:435:6
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:486:32
   C:\Program Files\Racket\share\pkgs\gui-lib\mred\private\wx\common\queue.rkt:634:3
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: win10, racket 8.3

**Additional context(or any ideas)**

Tested and can confirm this works fine on macOS - am unable to text linux.

**Comment by dannypsnl** [comment]
Interesting, but I didn't have Windows. @smallfont00 Can you help?

**Comment by dannypsnl** [comment]
[This](https://githubmemory.com/repo/willghatch/racket-rash/issues/74) seems like same problem

**Comment by smallfont00** [comment]
> Interesting, but I didn't have Windows. @smallfont00 Can you help?

Sure. but I am not free today so maybe tomorrow...😢

**Comment by smallfont00** [comment]
I don't think this is our problem @dannypsnl . I have tested pkg "from-template" alone and the same error happens.
![image](https://user-images.githubusercontent.com/33400198/141418514-5e595f79-6b9e-4ef2-a73b-ca19f0bd86d9.png)
Have you guys tested "from-template" on Linux? The path of "from-template.sh" can't be resolved in my Ubuntu. I have changed the source code of "from-template" and found out define-runtime-path is necessarily for my Ubuntu.

**Comment by dannypsnl** [comment]
@spdegabrielle so seems like this is not from sauron.

**Comment by spdegabrielle** [comment]
Thank you I'll check it out

**Comment by spdegabrielle** [comment]
Closing here - raised as https://github.com/nixin72/from-template/issues/12

**Comment by spdegabrielle** [comment]
FYI - this is fixed - If any windows users have trouble they should update the from-template package, either with the package manger in DrRacket or with 

`raco pkg update from-template`
