### ISSUE TITLE
sauron/project menus(maybe quickscript)

### ISSUE THREAD

**Issue by spdegabrielle** [racket-tw/sauron#175]
**Is your feature request related to a problem? Please describe.**
I have to go to the docs to find the keybindings, and I forget the ones I don't use often

**Describe the solution you'd like**
I'd like to have a menu/menus to make learning sauron keybindings easier.

**Describe alternatives you've considered**
Maybe doing sauron keybindings in Quickscript so they are optional?

**Comment by spdegabrielle** [comment]
cc: @metaxal

**Comment by dannypsnl** [comment]
Doing Sauron keybindings in quickscript sounds good, I don't have a strong opinion about keybinding choice.

**Comment by spdegabrielle** [comment]
> Doing Sauron keybindings in quickscript sounds good, I don't have a strong opinion about keybinding choice.

Does Sauron provide an API that quickscript scripts could call?

**Comment by dannypsnl** [comment]
Not sure, I need to look into quickscript

**Comment by dannypsnl** [comment]
https://github.com/racket-tw/sauron/blob/develop/tool/shortcut.rkt I think you can extract this as quickscript, and how can we provide default keybinding?

**Comment by dannypsnl** [comment]
tested, to few bindings can be done with quickscript, close for now. Feel free to reopen if needed
