### ISSUE TITLE
Bundle Sauron-IDE with files-viewer and DrComplete

### ISSUE THREAD

**Issue by spdegabrielle** [racket-tw/sauron#176]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I have to load multiple plugins to get the full IDE experience 

**Describe the solution you'd like**
Include files-viewer, DrComplete and Quickscript-extra with Sauron-IDE install

**Describe alternatives you've considered**
Use the quickscript project and completion features instead, but it is not as good as SauronIDE.

cc: @metaxal @yjqww6 @Syntacticlosure

**Comment by dannypsnl** [comment]
I reimplement files-viewer in Sauron is because project analysis, integrate it might not a simple process I guess.

**Comment by spdegabrielle** [comment]
I was thinking of creating a new package that installs Sauron-IDE, DrComplete & Files-Viewer.

Does that sound ok to you?

**Comment by dannypsnl** [comment]
Or add DrComplete into Sauron dependencies? I'm ok with this solution. About file-viewer, I think need deeper discussion.

**Comment by spdegabrielle** [comment]
Yes. I like File Viewer, but I would like it to extend the tree views to include __`define`’s__ within the current file or files across the currently selected project like you see in other modern IDE’s.

**Comment by dannypsnl** [comment]
Does file-viewer provide `define`s? A problem is that is really useless from my experience, another is I would like to provide new tabview for it, rather than put in file-viewer

**Comment by spdegabrielle** [comment]
File Viewer does not provide defines, but still I find it useful.

- I was thinking the tree view in files viewer would be ideal for the defines currently in the `(define ...)` button.
- 
https://docs.racket-lang.org/drracket/buttons.html

> Beside the filename button is a (define ...) button for a pop-up menu of names that are defined in the definitions window. Selecting an item from the menu moves the insertion point (blinking caret) to the corresponding definition.

**Comment by dannypsnl** [comment]
Maybe you can make one?

**Comment by dannypsnl** [comment]
BTW, #63 is also why I didn't integrate DrComplete, I was thinking to provide a more extensible completion

**Comment by dannypsnl** [comment]
@spdegabrielle would you mind I close this issue? I just bundle drcomplete in 6b4a4f3f8297709f0280b3806cf938045c0117bd, but files-viewer will conflict with current implementation.

**Comment by spdegabrielle** [comment]
I'm happy for you to close this issue
