### ISSUE TITLE
[bug] Contract violation when closing DrRacket's preferences

### ISSUE THREAD

**Issue by tinkerng** [racket-tw/sauron#190]
**Describe the bug**
If no project is loaded, trying to exit the DrRacket's preferences without saving changes causes a contract violation, making the window impossible to close.

**To Reproduce**
1. Have **sauron:unit** loaded (editor/keyword/repl don't influence the result) but no project open (independent files don't matter);
2. Open the Preferences and try to close it without saving changes (having made any or not doesn't matter) by either pressing ESC or clicking on "Undo Changes and Close";
3. You should get the error message and be unable to close the window even with methods that worked before it ("OK" and external shortcuts like ALT+F4) until restarting DrRacket.

**Expected behavior**
The same that happens when **sauron:unit** isn't loaded: the Preference windows closes without error.

**Screenshots(or error message)**
`directory-list: contract violation
  expected: path-string?
  given: #f
  context...:
   /usr/share/racket/pkgs/sauron/project/refresh-collect.rkt:15:0: refresh-project
   /usr/share/racket/pkgs/gui-lib/framework/preferences.rkt:254:4: loop
   /usr/share/racket/pkgs/gui-lib/framework/preferences.rkt:251:0: check-callbacks
   /usr/share/racket/pkgs/gui-lib/framework/preferences.rkt:154:3
   /usr/share/racket/pkgs/gui-lib/framework/preferences.rkt:389:0: preferences:restore-prefs-snapshot
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /usr/share/racket/pkgs/gui-lib/framework/private/frame.rkt:503:4: on-close method in register-group-mixin
   /usr/share/racket/pkgs/gui-lib/framework/private/frame.rkt:218:4: close method in basic-mixin
   /usr/share/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /usr/share/racket/collects/ffi/unsafe/atomic.rkt:73:13
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:836:4: call-pre-on-char method in window%
   [repeats 4 more times]
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:816:4: dispatch-on-char method in window%
   /usr/share/racket/collects/ffi/unsafe/try-atomic.rkt:105:19
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt:222:31
   /usr/share/racket/collects/ffi/unsafe/try-atomic.rkt:45:6
   ...
`

**Desktop (please complete the following information):**
 - OS: Linux
 - Sauron versions: 6a434a6 and 7a7d2b2
 - Racket version: 8.4

**Additional context(or any ideas)**
Sorry if I'm reporting at the wrong place. I'm just getting started on Racket so I couldn't debug and all I can offer is "the error started after installing Sauron and everything works if I disable sauron:unit" and I couldn't find anything by searching here and elsewhere.

**Comment by dannypsnl** [comment]
For temporary, you can use
```
ps aux | grep DrRacket
kill -9 <pid>
```
to kill process. I would dig into how to fix, thanks for report!

**Comment by dannypsnl** [comment]
I think this is triggered by preferences update, though I cannot sure how it happened when `current-project` shouldn't get affected, anyway a simple checking in the callback should be enough for now. I will send PR quickly

**Comment by tinkerng** [comment]
Working like a charm after the update! Thank you very much @dannypsnl!
