### ISSUE TITLE
[bug] Backspace and Space causing errors in Find/View Log input fields

### ISSUE THREAD

**Issue by tinkerng** [racket-tw/sauron#191]
**Describe the bug**
1. Pressing `Backspace` in the Find input fields causes an error that prevents the text from being changed; same when pressing `Backspace` or `Space` in the View Log input fields.

**To Reproduce**
With **sauron:keyword** loaded (the other submodules don't affect this):
1. Press CTRL+F to start a search;
2. Press `Backspace` in the Find or the Replace input fields (`Del`, `Return` and `Space` work normally).

Alternatively:
1. Open the log panel;
2. In the environment variable input field, press `Backspace` for the error above or `Space` for a different one (`Del` works normally).

**Screenshots(or error message)**
Error 1 (`Backspace` in Find or View Log input fields):

```
Error running keybinding ...9/tool/shortcut.rkt:97:10

send: no such method
  method name: get-backward-sexp
  class name: find-text%
```

Error 2 (`Space` in View Log input fields only):

```
Error running keybinding ...9/tool/shortcut.rkt:162:12

send: no such method
  method name: insert
  class name: text-field%
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Sauron version: 7a7d2b2 and bc714d8
 - Racket version: 8.4

**Additional context(or any ideas)**
I checked /sauron/tool/shortcut.rkt, confirming the errors refer to methods in the respective line numbers, and that I have the required pkgs mentioned at the top.

**Comment by dannypsnl** [comment]
1. I think it's `alt+backspace`? since it's line 97.
2. I don't what's "View Log input fields", do you know how to call it out?

**Comment by dannypsnl** [comment]
By the way, they should be fine after #175 done, since quickscript only work on certain GUI part. I will try if that's enough

**Comment by tinkerng** [comment]
@dannypsnl, sorry I couldn't comment before the release. I've updated and there was a change, but the issue isn't gone. `Space` still causes the same error in the Log but, with 94b418e, `Backspace` stopped working altogether both there and in Find/Replace (on the bright side, the error *is* gone :smile:) while **sauron:keyword** is active. Still responsive in the rest of the interface.

> 1. I think it's `alt+backspace`? since it's line 97.

Yes and no, I think? I'm only pressing `Backspace`, but I've noticed that the key does work like `ALT+Backspace` (i.e. deleting words instead of letters) in the definitions window and the REPL when **sauron:keyword** is active. I figured that could be a feature, like the auto-closing of parentheses, but maybe it's an unintended remapping of `Backspace` to `ALT+Backspace`?
 
> 2. I don't what's "View Log input fields", do you know how to call it out?

Sorry for the confusion, I meant the logger pane accessed on View menu > Show Log. The error happens when typing `Space` in the field where the logging level can be edited (from the default "error debug@GC debug@PLaneT").

**Comment by dannypsnl** [comment]
I simply close `alt+backspace` in those editors, I cannot reproduce your only pressing `backspace` problem on macOS. @smallfont00, would you like to test this?

For view log, I think I will simply by pass events as previous fix

**Comment by dannypsnl** [comment]
I think that's really possible that your `alt` is get pressed but not by your hand. I have met such problem before, the root cause is the key shaft stuck.

**Comment by tinkerng** [comment]
> I cannot reproduce your only pressing `backspace` problem on macOS.

Is it deleting text normally in those fields? For me only `ctrl+backspace` works there (clears everything from cursor to beginning) but `backspace` and `alt+backspace` do nothing.

**Comment by dannypsnl** [comment]
Yes, `backspace` worked normally from my side. Of course, `alt+backspace` shouldn't work right now.

**Comment by dannypsnl** [comment]
@tinkerng let's see if this version could solve the problem, if yes then I will release v1.3.1~~~

**Comment by tinkerng** [comment]
@dannypsnl, it didn't. Now pressing `backspace`, `alt+backspace` or `space` in either the Find/Replace (where `space` used to work) and the Log fields results in this error:

```
Error running keybinding ...n-9999/shortcut.rkt:{85:10, 150:1}

Send: no such method
  method-name: get-backward-sexp
  class-name: find-text%
```

Same method, `get-backward-sexp`, in every case, but pointing to line/column 85:10 for `backspace`/`alt+backspace` and 150:1 for `space`.

**Comment by dannypsnl** [comment]
Guess you can try db1300120ee47fd44a92c7a55035874b4120c360, those classes are private in framework, so I cannot simply check by `is-a?` function. And I send proper event to handle fall back case now.

**Comment by smallfont00** [comment]
db13001 does fix the problem on my Windows 11.

**Comment by tinkerng** [comment]
Also fixed on Linux, @dannypsnl. You're the best!
