### ISSUE TITLE
[bug] [minor] Error when canceling Open Documentation (c+d)

### ISSUE THREAD

**Issue by tinkerng** [racket-tw/sauron#196]
**Describe the bug**

Closing the Open Documentation window (`c+d`) without loading anything, or using the shortcut on read-only files, results in a contract violation error.

**To Reproduce**
1. Press `c+d` to bring up the open documentation window;
2. If the file is read-only, step 1 will be enough; else:
3. Close the window without actually loading a documentation file.

**Screenshots(or error message)**
```
Error running keybinding ...n-9999/shortcut.rkt:141:1

path->complete-path: contract violation
  expected: (or/c path-string? path-for-some-system?)
  given: '(form ((lib "racket/private/class-internal.rkt") send))
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Sauron version: db13001
 - Racket version: 8.4

**Additional context(or any ideas)**

Minor since it doesn't seem to have any effect other than an error message. It's a variation of #190, so please let me know if commenting on the other issue would have been better than opening this one and apologies if that's the case.

**Comment by dannypsnl** [comment]
It's fine, though they might have the same reason, but still different bugs from my view. Since they're different pieces of code and different functionalities.

**Comment by dannypsnl** [comment]
This is a fun one, I don't remember doc format is like that before XD!

**Comment by dannypsnl** [comment]
You can check now~~~~

**Comment by tinkerng** [comment]
Same error but different input, @dannypsnl:

```
Error running keybinding ...n-9999/shortcut.rkt:141:1

path->complete-path: contract violation
  expected: (or/c path-string? path-for-some-system?)
  given: #f
```

**Comment by dannypsnl** [comment]
I cannot reproduce this one, do you mind showing video?
