### ISSUE TITLE
[terminal] init

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#21]
- [ ] Another panel
- [ ] Bottom of IDE
- [ ] Multiple Tab
- [ ] Start path: Project path
- [ ] Interactive

https://docs.racket-lang.org/mrlib/Terminal_Window.html

**Comment by smallfont00** [comment]
i am sorry😢

**Comment by dannypsnl** [comment]
The result is not as good as expected, other terminal emulators like iTerm2 are better, so close the issue. Feel free to reopen if you can make a draft experience great.
