### ISSUE TITLE
Editor left in edit-sequence

### ISSUE THREAD

**Issue by jasonhemann** [racket-tw/sauron#214]
I just installed and restarted sauron on my 8.6 version of DrRacket. I pressed c+m to open a project, and received the following message:

```
Error running keybinding ...sauron/shortcut.rkt:132:11

Editor left in edit-sequence

```

**Expected behavior**
I hadn't expected the error message to pop up.

**Screenshots(or error message)**
![image](https://user-images.githubusercontent.com/1329370/186470532-ba8eccfa-e052-4a00-9379-f820b099c080.png)

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - Sauron version: most recent on pkg server
 - Racket version: 8.6

**Additional context(or any ideas)**

**Comment by dannypsnl** [comment]
I cannot reproduce this bug, would you mind to comment out https://github.com/racket-tw/sauron/blob/develop/tool/editor.rkt#L18 this line and do it again?

**Comment by jasonhemann** [comment]
Thank you very much for your help. I now see the following error message:

![image](https://user-images.githubusercontent.com/1329370/186477406-148cd33c-9f3c-44ed-ac45-8b7957204d73.png)

**Comment by dannypsnl** [comment]
Emmm, interesting, that's only point I know place uses edit-sequence

**Comment by jasonhemann** [comment]
This appears to have been an artifact of [another issue I was facing in DrRacket](https://github.com/racket/drracket/issues/575) rather than solely an issue with sauron itself. Sauron was just the means to trigger it.

**Comment by dannypsnl** [comment]
Oh! I see, the problem is because `sauron` bundle `drcomplete`
