### ISSUE TITLE
c+d, etc. presumes filename exists

### ISSUE THREAD

**Issue by jasonhemann** [racket-tw/sauron#215]
I see an error when running the [shortcut for ctrl+d](https://github.com/racket-tw/sauron/blob/7ba4130458166c975e35889759d0643e6cfb9a3c/shortcut.rkt#L143). Since `get-filename` can return `#f` when the editor has no filename, I think that has to be checked for like in [c+s](https://github.com/racket-tw/sauron/blob/7ba4130458166c975e35889759d0643e6cfb9a3c/shortcut.rkt#L42). I believe it's the same problem for `c+b` except it comes from [`jump-to-definition`](https://github.com/racket-tw/sauron/blob/7ba4130458166c975e35889759d0643e6cfb9a3c/jump-to-def.rkt#L12).

**Comment by dannypsnl** [comment]
The correct behavior should be `c+d` and `c+b` works for untitled file too, but I haven't researched how to check untitled files with `annotation<%>` API, so the code is left like that.

I'm ok to apply a check for now, would you mind sending a PR? Which
1. check filename exists in `c+d` and `c+b`
2. left `FIXME` comment for `c+d` and `c+b`

**Comment by jasonhemann** [comment]
Thank you, apologize that I didn't get to this before you did!
