### ISSUE TITLE
[Release] Provide Binary link in release page

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#23]
I need to research how to do this, but currently, this is not the most important to do.

**Comment by spdegabrielle** [comment]
https://docs.racket-lang.org/raco/exe.html

`raco exe --gui hello.rkt`

But doing it from DrRacket simplifies the process of doing it manually.


![image](https://user-images.githubusercontent.com/108047/90660405-c4bfad80-e23d-11ea-9e3d-f8567b0c118d.png)
