### ISSUE TITLE
add contribution guidelines

### ISSUE THREAD

**Issue by spdegabrielle** [racket-tw/sauron#25]
Should include 

I think as a minimum

- [x] Contribution Licence terms
- [x] Code of Conduct
- [x] Coding Standards
- [x] PR Standards

### My suggestions; 

To be compatible with Racket I'd suggest the following for Licence terms; 

> By making a contribution, you are agreeing that your contribution is licensed under the Apache 2.0 and MIT licenses. Those licenses are available in this repository in the files LICENSE-APACHE.txt and LICENSE-MIT.txt.

Follow the GitHub guidance on Code of Conduct.

Follow the Racket Style Guide and Contribution Guide for the last two.

**Comment by dannypsnl** [comment]
What would be APACHE allowed and MIT don't?

**Comment by spdegabrielle** [comment]
I’m suggesting following the dual licensing lead of racket

**Comment by dannypsnl** [comment]
Done
