### ISSUE TITLE
[editor] scrolling speed

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#39]
Compare with VSCode, seems like slower

**Comment by yjqww6** [comment]
note that `set-scroll-via-copy` of editor-canvas could somewhat improve scrolling speed, especially on Mac, but it would also complicate handling of bitmap cache.
files-viewer used to face similar slow scrolling problem: https://github.com/MatrixForChange/files-viewer/commit/5a1016894db4795c25684c817326f28fa788d196

**Comment by dannypsnl** [comment]
Depends on DrRacket now
