### ISSUE TITLE
[Feature] c+e A naive REPL

### ISSUE THREAD

**Issue by dannypsnl** [racket-tw/sauron#6]
Naive means nothing more, just a REPL. Advanced features should be done in others issues.

**Comment by dannypsnl** [comment]
NOTE: Maybe trigger it on save?

**Comment by dannypsnl** [comment]
https://github.com/racket-templates/guiapp/blob/master/main.rkt seems like a good start.

**Comment by spdegabrielle** [comment]
Note the paper https://www2.ccs.neu.edu/racket/pubs/icfp99-ffkf.pdf refers to an earlier version before the introduction of the module system.

**Comment by dannypsnl** [comment]
Need to figure out which is a better way for executing the whole program and get output.

**Comment by dannypsnl** [comment]
Since the target already archive, just close this first. Advanced issues leave for other issues.
